### ISSUE TITLE
Problems with Visual Studio 2015 and Microsoft Edge

### ISSUE THREAD

**Issue by paulguz** [chrisisbeef/jquery-encoder#14]
Hi,  

jquery-encoder seems to be causing problems in Microsoft Edge, and Visual Studio 2015.

I can't describe the problem in Edge as it goes away when debugging, except that Edge may refuse to load a web application that uses encoder.js.

If encoder.js is present in any Visual Studio 2015 project, VS2015 crashes when attempting to edit any JavaScript file.  

MIcrosoft have been informed and are actively investigating the VS2015 issue.

Regards,

Paul

**Comment by patrickkettner** [comment]
@paulguz can you provide an example of the issue with edge?

**Comment by paulguz** [comment]
@patrickkettner, thanks for responding.

I've set up a version of our software at http://datapadev2.cloudapp.net/datapa/.

You'll see the problem in Edge straight away.  Disappointingly there problem does not occur if you open the F12 dev tool, and there are no console errors (a few warnings, but nothing relevant).

**Comment by ketamin** [comment]
Hello, I ran into the same problem, it seems Edge reloads the page twice or more and fails. With debugger-console open, the Edge won't have any problems. This is my question to the Edge team:
https://connect.microsoft.com/IE/feedback/details/1662734/edge-cant-display-page-if-javascript-library-jquery-encoder-will-be-loaded-via-jquery

Uuuups, I have to answer them back - didn't got any mail or something o.O
Maybe @paulguz you can answer with your link?

**Comment by paulguz** [comment]
@ketamin , I've commented on your Microsoft Connect post.  Please note I've moved my example to http://datapadev2.cloudapp.net/DataPAEncoder/

Glad to see that it's not just me.

**Comment by chrisisbeef** [comment]
Great to see you guys working on this - keep us posted here of any progress you make on this issue please!

**Comment by patrickkettner** [comment]
@paulguz the domain seems to be down - can you double check?

**Comment by paulguz** [comment]
@patrickkettner It's back up now; sorry for the slow response, I've been away.

Note the change in URL from my original response to you.  It is now

http://datapadev2.cloudapp.net/DataPAEncoder/

**Comment by paulguz** [comment]
Good news: with the November update to Windows 10, it seems that the problem with Edge is now gone.  Also, I've been informed by Microsoft that the problem with Visual Studio 2015 is also fixed with Update 1 (although I've not tried it yet as it is still at RC stage).

@ketamin, have you run the November update yet and if so, can you confirm the problem has gone?

**Comment by chrisisbeef** [comment]
@paulguz @ketamin @patrickkettner - Can one of you confirm that this issue is resolved? It seems like it has been determined with relative confidence that this is an upstream issue, so I would like to close this issue out if that's okay with you all.

**Comment by paulguz** [comment]
@chrisisbeef For me, the problem is gone, in both Edge and Visual Studio 2015.

**Comment by chrisisbeef** [comment]
Closing issue - thanks for following up on this @paulguz @ketamin @patrickkettner
