### ISSUE TITLE
encodeForHMTL() with immune_html

### ISSUE THREAD

**Issue by ricmetal** [chrisisbeef/jquery-encoder#2]
hi
i'm trying to allow the HTML br tag to be treated as a line break when using the encoder for printing text. if this is not a possibility with the jQuery plugin, i would like to ask for a request. i'm still looking into the encoder plugin. thanks

**Comment by chrisisbeef** [comment]
@ricmetal - This should be handled in a sanitization library (such as Google Caja - https://developers.google.com/caja/?hl=en). I am going to close this issue. Thanks!
